name: Semantic Release
on:
  push:
    branches:
      - main

jobs:

  semantic-release:
    name: Run Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout latest
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CREATE_RELEASE }}
      - run: npm ci
      - run: npm run build
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@master
        with:
          semantic_version: 17.0.4
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/git@9.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_RELEASE }}
